import { BASE_PATH } from "./constants";

export const KATEGORIJE = [
  { id: "burgeri", sr: "Burgeri", en: "Burgers" },
  { id: "pice", sr: "Pice", en: "Pizzas" },
  { id: "salate", sr: "Salate", en: "Salads" },
  { id: "deserti", sr: "Deserti", en: "Desserts" },
  { id: "restoran", sr: "Restoran", en: "Restaurant" },
];

export const JELOVNIK = [
  {
    id: "1",
    naziv: { sr: "Gurmanska pljeskavica", en: "Gourmet Burger" },
    opis: {
      sr: "Kačkavalj, slaninica, tucana paprika, luk...",
      en: "Cheese, bacon, roasted peppers, onion...",
    },
    sastojci: {
      sr: "300g pljeskavica od junećeg mesa, pecivo sa susamom, kačkavalj, slaninica, tucana paprika, crni luk, zelena salata, domaći sos.",
      en: "300g beef patty, sesame bun, cheese, bacon, roasted peppers, red onion, lettuce, house sauce.",
    },
    tagovi: ["ljuto"],
    cena: 450,
    kategorija: "burgeri",
    vreme_pripreme: 15,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "2",
    naziv: { sr: "Margarita Pica", en: "Margherita Pizza" },
    opis: {
      sr: "Pelat, kačkavalj, masline, origano...",
      en: "Tomato sauce, cheese, olives, oregano...",
    },
    sastojci: {
      sr: "Domaće testo, pelat sos od paradajza, kačkavalj, masline, sveži bosiljak, origano, maslinovo ulje.",
      en: "House dough, tomato sauce, cheese, olives, fresh basil, oregano, olive oil.",
    },
    tagovi: ["vegetarijansko", "popularno"],
    cena: 800,
    kategorija: "pice",
    vreme_pripreme: 25,
    slika_url: `${BASE_PATH}/images/margarita.webp`,
  },
  {
    id: "3",
    naziv: { sr: "Cezar salata", en: "Caesar Salad" },
    opis: {
      sr: "Piletina, krutoni, cezar dresing...",
      en: "Chicken, croutons, caesar dressing...",
    },
    sastojci: {
      sr: "Piletina na žaru, listovi rimske salate, krutoni, parmezan, cezar dresing.",
      en: "Grilled chicken, romaine lettuce, croutons, parmesan, caesar dressing.",
    },
    tagovi: ["bez_glutena"],
    cena: 650,
    kategorija: "salate",
    vreme_pripreme: 10,
    slika_url: `${BASE_PATH}/images/cezar-salata.webp`,
  },
  {
    id: "4",
    naziv: { sr: "Domaća palačinka", en: "Homemade Pancake" },
    opis: {
      sr: "Nutela, plazma, šlag...",
      en: "Nutella, biscuit crumbs, whipped cream...",
    },
    sastojci: {
      sr: "Tanka palačinka, čokoladni krem, mrvice plazma keksa, šlag, listić nane.",
      en: "Thin pancake, chocolate spread, crushed biscuits, whipped cream, mint leaf.",
    },
    tagovi: ["vegetarijansko"],
    cena: 350,
    kategorija: "deserti",
    vreme_pripreme: 8,
    slika_url: `${BASE_PATH}/images/palacinka.webp`,
  },
  {
    id: "5",
    naziv: { sr: "Domaća palačinka", en: "Homemade Pancake" },
    opis: {
      sr: "Nutela, plazma, šlag...",
      en: "Nutella, biscuit crumbs, whipped cream...",
    },
    sastojci: {
      sr: "Tanka palačinka, čokoladni krem, mrvice plazma keksa, šlag, listić nane.",
      en: "Thin pancake, chocolate spread, crushed biscuits, whipped cream, mint leaf.",
    },
    tagovi: ["sadrzi_orasaste"],
    cena: 350,
    kategorija: "deserti",
    vreme_pripreme: 8,
    slika_url: `${BASE_PATH}/images/palacinka.webp`,
  },
  {
    id: "6",
    naziv: { sr: "Domaća palačinka", en: "Homemade Pancake" },
    opis: {
      sr: "Nutela, plazma, šlag...",
      en: "Nutella, biscuit crumbs, whipped cream...",
    },
    sastojci: {
      sr: "Tanka palačinka, čokoladni krem, mrvice plazma keksa, šlag, listić nane.",
      en: "Thin pancake, chocolate spread, crushed biscuits, whipped cream, mint leaf.",
    },
    tagovi: ["sadrzi_laktozu"],
    cena: 350,
    kategorija: "deserti",
    vreme_pripreme: 8,
    slika_url: `${BASE_PATH}/images/palacinka.webp`,
  },
  {
    id: "7",
    naziv: { sr: "Domaća palačinka", en: "Homemade Pancake" },
    opis: {
      sr: "Nutela, plazma, šlag...",
      en: "Nutella, biscuit crumbs, whipped cream...",
    },
    cena: 350,
    kategorija: "deserti",
    vreme_pripreme: 8,
    slika_url: `${BASE_PATH}/images/palacinka.webp`,
  },
  {
    id: "8",
    naziv: { sr: "Domaća palačinka", en: "Homemade Pancake" },
    opis: {
      sr: "Nutela, plazma, šlag...",
      en: "Nutella, biscuit crumbs, whipped cream...",
    },
    cena: 350,
    kategorija: "deserti",
    vreme_pripreme: 8,
    slika_url: `${BASE_PATH}/images/palacinka.webp`,
  },
  {
    id: "9",
    naziv: { sr: "Domaća palačinka", en: "Homemade Pancake" },
    opis: {
      sr: "Nutela, plazma, šlag...",
      en: "Nutella, biscuit crumbs, whipped cream...",
    },
    cena: 350,
    kategorija: "deserti",
    vreme_pripreme: 8,
    slika_url: `${BASE_PATH}/images/palacinka.webp`,
  },
  {
    id: "10",
    naziv: { sr: "Gurmanska pljeskavica", en: "Gourmet Burger" },
    opis: {
      sr: "Kačkavalj, slaninica, tucana paprika, luk...",
      en: "Cheese, bacon, roasted peppers, onion...",
    },
    cena: 450,
    kategorija: "burgeri",
    vreme_pripreme: 15,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "11",
    naziv: { sr: "Margarita Pica", en: "Margherita Pizza" },
    opis: {
      sr: "Pelat, kačkavalj, masline, origano...",
      en: "Tomato sauce, cheese, olives, oregano...",
    },
    cena: 800,
    kategorija: "pice",
    vreme_pripreme: 25,
    slika_url: `${BASE_PATH}/images/margarita.webp`,
  },
  {
    id: "12",
    naziv: { sr: "Cezar salata", en: "Caesar Salad" },
    opis: {
      sr: "Piletina, krutoni, cezar dresing...",
      en: "Chicken, croutons, caesar dressing...",
    },
    cena: 650,
    kategorija: "salate",
    vreme_pripreme: 10,
    slika_url: `${BASE_PATH}/images/cezar-salata.webp`,
  },
  {
    id: "13",
    naziv: { sr: "Gurmanska pljeskavica", en: "Gourmet Burger" },
    opis: {
      sr: "Kačkavalj, slaninica, tucana paprika, luk...",
      en: "Cheese, bacon, roasted peppers, onion...",
    },
    cena: 450,
    kategorija: "burgeri",
    vreme_pripreme: 15,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "14",
    naziv: { sr: "Margarita Pica", en: "Margherita Pizza" },
    opis: {
      sr: "Pelat, kačkavalj, masline, origano...",
      en: "Tomato sauce, cheese, olives, oregano...",
    },
    cena: 800,
    kategorija: "pice",
    vreme_pripreme: 25,
    slika_url: `${BASE_PATH}/images/margarita.webp`,
  },
  {
    id: "15",
    naziv: { sr: "Cezar salata", en: "Caesar Salad" },
    opis: {
      sr: "Piletina, krutoni, cezar dresing...",
      en: "Chicken, croutons, caesar dressing...",
    },
    cena: 650,
    kategorija: "salate",
    vreme_pripreme: 10,
    slika_url: `${BASE_PATH}/images/cezar-salata.webp`,
  },
  {
    id: "16",
    naziv: { sr: "Gurmanska pljeskavica", en: "Gourmet Burger" },
    opis: {
      sr: "Kačkavalj, slaninica, tucana paprika, luk...",
      en: "Cheese, bacon, roasted peppers, onion...",
    },
    cena: 450,
    kategorija: "burgeri",
    vreme_pripreme: 15,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "17",
    naziv: { sr: "Margarita Pica", en: "Margherita Pizza" },
    opis: {
      sr: "Pelat, kačkavalj, masline, origano...",
      en: "Tomato sauce, cheese, olives, oregano...",
    },
    cena: 800,
    kategorija: "pice",
    vreme_pripreme: 25,
    slika_url: `${BASE_PATH}/images/margarita.webp`,
  },
  {
    id: "18",
    naziv: { sr: "Cezar salata", en: "Caesar Salad" },
    opis: {
      sr: "Piletina, krutoni, cezar dresing...",
      en: "Chicken, croutons, caesar dressing...",
    },
    cena: 650,
    kategorija: "salate",
    vreme_pripreme: 10,
    slika_url: `${BASE_PATH}/images/cezar-salata.webp`,
  },

  // ============ RESTORAN - DORUČAK ============
  {
    id: "r1",
    naziv: { sr: "Domaće prženice", en: "Homemade French Toast" },
    opis: {
      sr: "Sezonska salata, pavlaka.",
      en: "Seasonal salad, sour cream.",
    },
    tagovi: [],
    cena: 420,
    kategorija: "restoran",
    podkategorija: "dorucak",
    vreme_pripreme: 12,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r2",
    naziv: {
      sr: "Domaće punjene prženice",
      en: "Homemade Stuffed French Toast",
    },
    opis: {
      sr: "Pečenica, sezonska salata, kačkavalj, pavlaka.",
      en: "Smoked pork loin, seasonal salad, cheese, sour cream.",
    },
    tagovi: [],
    cena: 520,
    kategorija: "restoran",
    podkategorija: "dorucak",
    vreme_pripreme: 12,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r3",
    naziv: { sr: "Omlet po izboru", en: "Omelette of Choice" },
    opis: { sr: "Prilog po izboru + 3 jaja.", en: "Choice of side + 3 eggs." },
    tagovi: ["vegetarijansko"],
    cena: 420,
    kategorija: "restoran",
    podkategorija: "dorucak",
    vreme_pripreme: 12,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r4",
    naziv: { sr: "Domaća kajgana", en: "Homemade Scrambled Eggs" },
    opis: {
      sr: "Sezonsko povrće, 3 jaja, pavlaka, sir.",
      en: "Seasonal vegetables, 3 eggs, sour cream, cheese.",
    },
    tagovi: ["vegetarijansko"],
    cena: 400,
    kategorija: "restoran",
    podkategorija: "dorucak",
    vreme_pripreme: 12,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r5",
    naziv: { sr: "Klub sendvič", en: "Club Sandwich" },
    opis: {
      sr: "Dresing, paradajz, pečenica, iceberg, čedar sir.",
      en: "Dressing, tomato, smoked pork loin, iceberg lettuce, cheddar cheese.",
    },
    tagovi: [],
    cena: 570,
    kategorija: "restoran",
    podkategorija: "dorucak",
    vreme_pripreme: 12,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r6",
    naziv: { sr: "Bellavista doručak", en: "Bellavista Breakfast" },
    opis: {
      sr: "Slanina, kobasica, 2 jaja, sir, kajmak, urnebes.",
      en: "Bacon, sausage, 2 eggs, cheese, kaymak, urnebes spread.",
    },
    tagovi: ["popularno"],
    cena: 520,
    kategorija: "restoran",
    podkategorija: "dorucak",
    vreme_pripreme: 15,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r7",
    naziv: {
      sr: "Nacionalni doručak za dvoje",
      en: "National Breakfast for Two",
    },
    opis: {
      sr: "Kobasica, sezonska salata, slanina, 4 jaja, pohovani kačkavalj, sir, senf.",
      en: "Sausage, seasonal salad, bacon, 4 eggs, breaded cheese, cheese, mustard.",
    },
    tagovi: [],
    cena: 1300,
    kategorija: "restoran",
    podkategorija: "dorucak",
    vreme_pripreme: 18,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r8",
    naziv: { sr: "Seoski klasik", en: "Village Classic" },
    opis: {
      sr: "Palenta, slanina, sir, jaje.",
      en: "Polenta, bacon, cheese, egg.",
    },
    tagovi: [],
    cena: 350,
    kategorija: "restoran",
    podkategorija: "dorucak",
    vreme_pripreme: 12,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r9",
    naziv: { sr: "Zalogaj detinjstva", en: "Taste of Childhood" },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 350,
    kategorija: "restoran",
    podkategorija: "dorucak",
    vreme_pripreme: 12,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r10",
    naziv: { sr: "Uštipci slatki/slani", en: "Fried Dough - Sweet/Savory" },
    opis: {
      sr: "Krem/džem, ajvar/pavlaka.",
      en: "Chocolate spread/jam, ajvar/sour cream.",
    },
    tagovi: ["vegetarijansko"],
    cena: 450,
    kategorija: "restoran",
    podkategorija: "dorucak",
    vreme_pripreme: 12,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r11",
    naziv: { sr: "Komplet lepinja", en: "Komplet Lepinja Bread" },
    opis: { sr: "Pretop, jaje, kajmak.", en: "Pork cracklings, egg, kaymak." },
    tagovi: [],
    cena: 450,
    kategorija: "restoran",
    podkategorija: "dorucak",
    vreme_pripreme: 12,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r12",
    naziv: { sr: "Naša komplet lepinja", en: "Our Komplet Lepinja Bread" },
    opis: {
      sr: "Pečenica ili kulen, pretop, jaje, kajmak.",
      en: "Smoked pork loin or kulen sausage, pork cracklings, egg, kaymak.",
    },
    tagovi: [],
    cena: 600,
    kategorija: "restoran",
    podkategorija: "dorucak",
    vreme_pripreme: 12,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },

  // ============ RESTORAN - TOPLA PREPORUKA ============
  {
    id: "r13",
    naziv: { sr: "Pohovani kačkavalj", en: "Breaded Cheese" },
    opis: { sr: "", en: "" },
    tagovi: ["vegetarijansko"],
    cena: 670,
    kategorija: "restoran",
    podkategorija: "topla_preporuka",
    vreme_pripreme: 15,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r14",
    naziv: { sr: "Pečurke na žaru", en: "Grilled Mushrooms" },
    opis: { sr: "", en: "" },
    tagovi: ["vegetarijansko", "vegan"],
    cena: 550,
    kategorija: "restoran",
    podkategorija: "topla_preporuka",
    vreme_pripreme: 15,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r15",
    naziv: {
      sr: "Pečurke na žaru punjene kajmakom",
      en: "Grilled Mushrooms Stuffed with Kaymak",
    },
    opis: { sr: "Punjene kajmakom.", en: "Stuffed with kaymak." },
    tagovi: ["vegetarijansko"],
    cena: 680,
    kategorija: "restoran",
    podkategorija: "topla_preporuka",
    vreme_pripreme: 15,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r16",
    naziv: {
      sr: "Pohovana paprika punjena sirom i čvarcima",
      en: "Breaded Pepper Stuffed with Cheese and Cracklings",
    },
    opis: {
      sr: "Punjena sirom i čvarcima.",
      en: "Stuffed with cheese and pork cracklings.",
    },
    tagovi: [],
    cena: 700,
    kategorija: "restoran",
    podkategorija: "topla_preporuka",
    vreme_pripreme: 15,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r17",
    naziv: { sr: "Miročki grilovani sir", en: "Miroč Grilled Cheese" },
    opis: { sr: "", en: "" },
    tagovi: ["vegetarijansko"],
    cena: 580,
    kategorija: "restoran",
    podkategorija: "topla_preporuka",
    vreme_pripreme: 15,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r18",
    naziv: {
      sr: "Grilovane tikvice sa sirom i pršutom",
      en: "Grilled Zucchini with Cheese and Prosciutto",
    },
    opis: { sr: "Sa sirom i pršutom.", en: "With cheese and prosciutto." },
    tagovi: [],
    cena: 680,
    kategorija: "restoran",
    podkategorija: "topla_preporuka",
    vreme_pripreme: 15,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r19",
    naziv: { sr: "Patlidžan parmigiana", en: "Eggplant Parmigiana" },
    opis: {
      sr: "Mocarela zapečena sa plavim patlidžanom, pelat.",
      en: "Mozzarella baked with eggplant, tomato sauce.",
    },
    sastojci: {
      sr: "Najtoplija preporuka kuhinje - mocarela zapečena sa plavim patlidžanom, pelat sos od paradajza.",
      en: "The kitchen's warmest recommendation - mozzarella baked with eggplant, tomato sauce.",
    },
    tagovi: ["popularno", "vegetarijansko"],
    cena: 730,
    kategorija: "restoran",
    podkategorija: "topla_preporuka",
    vreme_pripreme: 18,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },

  // ============ RESTORAN - JELA OD PILETINE ============
  {
    id: "r20",
    naziv: {
      sr: "Pileće belo na žaru 300g",
      en: "Grilled Chicken Breast 300g",
    },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 850,
    kategorija: "restoran",
    podkategorija: "pile",
    vreme_pripreme: 22,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r21",
    naziv: {
      sr: "Dimljeni batak na pire krompiru 350g",
      en: "Smoked Chicken Leg with Mashed Potatoes 350g",
    },
    opis: { sr: "Na pire krompiru.", en: "Served with mashed potatoes." },
    tagovi: [],
    cena: 950,
    kategorija: "restoran",
    podkategorija: "pile",
    vreme_pripreme: 22,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r22",
    naziv: {
      sr: "Pileća karađorđeva 250g",
      en: "Chicken Karađorđeva Schnitzel 250g",
    },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 930,
    kategorija: "restoran",
    podkategorija: "pile",
    vreme_pripreme: 22,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r23",
    naziv: { sr: "Bečka šnicla 400g", en: "Vienna Schnitzel 400g" },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 930,
    kategorija: "restoran",
    podkategorija: "pile",
    vreme_pripreme: 22,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r24",
    naziv: { sr: "Crispy piletina 350g", en: "Crispy Chicken 350g" },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 900,
    kategorija: "restoran",
    podkategorija: "pile",
    vreme_pripreme: 22,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r25",
    naziv: {
      sr: "Punjeno pileće belo sa dimljenim sirom, rukolom i paprikom 450g",
      en: "Chicken Breast Stuffed with Smoked Cheese, Arugula and Pepper 450g",
    },
    opis: {
      sr: "Dimljeni sir, rukola, paprika.",
      en: "Smoked cheese, arugula, peppers.",
    },
    tagovi: [],
    cena: 1000,
    kategorija: "restoran",
    podkategorija: "pile",
    vreme_pripreme: 25,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r26",
    naziv: {
      sr: "Piletina u sosu od 4 vrste sira 350g",
      en: "Chicken in Four-Cheese Sauce 350g",
    },
    opis: { sr: "Sos od 4 vrste sira.", en: "Four-cheese sauce." },
    tagovi: [],
    cena: 950,
    kategorija: "restoran",
    podkategorija: "pile",
    vreme_pripreme: 22,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r27",
    naziv: {
      sr: "Piletina u sosu od pečurki 350g",
      en: "Chicken in Mushroom Sauce 350g",
    },
    opis: { sr: "Sos od pečurki.", en: "Mushroom sauce." },
    tagovi: [],
    cena: 950,
    kategorija: "restoran",
    podkategorija: "pile",
    vreme_pripreme: 22,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r28",
    naziv: {
      sr: "Pileći paketići punjeni slaninom i kačkavaljem u sosu od kajmaka 450g",
      en: "Chicken Parcels Stuffed with Bacon and Cheese in Kaymak Sauce 450g",
    },
    opis: {
      sr: "Slanina, kačkavalj, sos od kajmaka.",
      en: "Bacon, cheese, kaymak sauce.",
    },
    tagovi: [],
    cena: 1050,
    kategorija: "restoran",
    podkategorija: "pile",
    vreme_pripreme: 25,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r29",
    naziv: { sr: "Pohovani štapići 300g", en: "Breaded Chicken Strips 300g" },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 880,
    kategorija: "restoran",
    podkategorija: "pile",
    vreme_pripreme: 20,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },

  // ============ RESTORAN - RIBA ============
  {
    id: "r30",
    naziv: { sr: "Smuđ 1kg", en: "Pikeperch 1kg" },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 3500,
    kategorija: "restoran",
    podkategorija: "riba",
    vreme_pripreme: 30,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r31",
    naziv: { sr: "Som 1kg", en: "Catfish 1kg" },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 3500,
    kategorija: "restoran",
    podkategorija: "riba",
    vreme_pripreme: 30,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r32",
    naziv: { sr: "Pastrmka fileti 1kg", en: "Trout Fillets 1kg" },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 4000,
    kategorija: "restoran",
    podkategorija: "riba",
    vreme_pripreme: 30,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r33",
    naziv: { sr: "Šaran 1kg", en: "Carp 1kg" },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 3200,
    kategorija: "restoran",
    podkategorija: "riba",
    vreme_pripreme: 30,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r34",
    naziv: { sr: "Orada porcija 450g", en: "Sea Bream Portion 450g" },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 1400,
    kategorija: "restoran",
    podkategorija: "riba",
    vreme_pripreme: 25,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r35",
    naziv: { sr: "Brancin porcija 450g", en: "Sea Bass Portion 450g" },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 1700,
    kategorija: "restoran",
    podkategorija: "riba",
    vreme_pripreme: 25,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
  {
    id: "r36",
    naziv: { sr: "Girice 300g", en: "Fried Smelt 300g" },
    opis: { sr: "", en: "" },
    tagovi: [],
    cena: 380,
    kategorija: "restoran",
    podkategorija: "riba",
    vreme_pripreme: 15,
    slika_url: `${BASE_PATH}/images/pljeskavica.webp`,
  },
];

// Podkategorije SAMO za "restoran" kategoriju - kad je izabrana, kupac prvo
// bira jednu od ovih pre nego što vidi stavke.
export const PODKATEGORIJE_RESTORAN = [
  { id: "dorucak", sr: "Doručak", en: "Breakfast" },
  { id: "topla_preporuka", sr: "Topla preporuka", en: "Hot Recommendations" },
  { id: "pile", sr: "Jela od piletine", en: "Chicken Dishes" },
  { id: "riba", sr: "Riba", en: "Fish" },
];

export const DODACI_PO_KATEGORIJI = {
  burgeri: [
    { id: "k1", naziv: { sr: "Kajmak", en: "Kaymak" }, cena: 80 },
    { id: "s1", naziv: { sr: "Slaninica", en: "Bacon" }, cena: 60 },
    {
      id: "d1",
      naziv: { sr: "Dupli kačkavalj", en: "Extra cheese" },
      cena: 100,
    },
  ],
  pice: [
    { id: "p1", naziv: { sr: "Ekstra sir", en: "Extra cheese" }, cena: 100 },
    { id: "p2", naziv: { sr: "Pečurke", en: "Mushrooms" }, cena: 80 },
    { id: "p3", naziv: { sr: "Šunka", en: "Ham" }, cena: 90 },
    {
      id: "p4",
      naziv: { sr: "Ljuta papričica", en: "Chili peppers" },
      cena: 50,
    },
  ],
  salate: [
    {
      id: "sl1",
      naziv: { sr: "Ekstra piletina", en: "Extra chicken" },
      cena: 120,
    },
    { id: "sl2", naziv: { sr: "Avokado", en: "Avocado" }, cena: 100 },
    { id: "sl3", naziv: { sr: "Feta sir", en: "Feta cheese" }, cena: 80 },
    { id: "sl4", naziv: { sr: "Susam", en: "Sesame seeds" }, cena: 40 },
  ],
  deserti: [
    { id: "de1", naziv: { sr: "Banana", en: "Banana" }, cena: 50 },
    { id: "de2", naziv: { sr: "Jagode", en: "Strawberries" }, cena: 70 },
    { id: "de3", naziv: { sr: "Lešnici", en: "Crushed hazelnuts" }, cena: 60 },
    {
      id: "de4",
      naziv: { sr: "Kugla sladoleda", en: "Scoop of ice cream" },
      cena: 90,
    },
  ],
};

// Tagovi na stavkama menija (npr. zeleni "VEGAN" plutajući preko slike).
// Dodaj "tagovi: ['vegan', 'sadrzi_orasaste']" (koliko god ključeva) na
// stavku u JELOVNIK-u.
export const TAGOVI_INFO = {
  // Ishrana - zelene nijanse
  vegan: { sr: "Vegan", en: "Vegan", boja: "bg-emerald-100 text-emerald-700" },
  vegetarijansko: {
    sr: "Vegetarijansko",
    en: "Vegetarian",
    boja: "bg-green-100 text-green-700",
  },
  bez_glutena: {
    sr: "Bez glutena",
    en: "Gluten-free",
    boja: "bg-sky-100 text-sky-700",
  },
  // Ukus - toplo/crveno
  ljuto: { sr: "Ljuto", en: "Spicy", boja: "bg-red-100 text-red-600" },
  // Alergeni - upozorenje, žuto/narandžasto
  sadrzi_orasaste: {
    sr: "Sadrži orašaste plodove",
    en: "Contains nuts",
    boja: "bg-orange-100 text-orange-700",
  },
  sadrzi_laktozu: {
    sr: "Sadrži laktozu",
    en: "Contains lactose",
    boja: "bg-yellow-100 text-yellow-700",
  },
  // Marketing - amber/pink
  novo: { sr: "Novo", en: "New", boja: "bg-amber-100 text-amber-700" },
  popularno: {
    sr: "Popularno",
    en: "Popular",
    boja: "bg-pink-100 text-pink-700",
  },
};

// ---- Mape za KUHINJU: uvek srpski naziv, bez obzira na jezik na kom je
// kupac naručio (kupac čuva lokalizovan naziv u samoj porudžbini radi svog
// prikaza, ali kuhinja gleda ove mape preko id_jela/id dodatka) ----
export const NAZIV_JELA_SR = Object.fromEntries(
  JELOVNIK.map((j) => [j.id, j.naziv.sr]),
);

export const NAZIV_DODATKA_SR = Object.fromEntries(
  Object.values(DODACI_PO_KATEGORIJI)
    .flat()
    .map((d) => [d.id, d.naziv.sr]),
);
